### PR TITLE
Review `huggingface_hub` integration

### PR DESCRIPTION
**Pull request by Wauplin**
Made a few changes to the `huggingface_hub` integration:
- bump `huggingface_hub` min dependency to a recent one that include bug fixes
- update authentication section in README.md
-  use `ModelCard` + `ModelCardData` => more concise + automatically handle encoding issues (typically `"\r\n"` vs `"\n"` newline encoding on Windows)
- set token in `HfApi` + reuse the client => avoid to set `token=token` in both `create_repo` and `upload_folder`
- do not upload a model card in `push_to_hub` => current implem' was uploading an empty one. Better to not upload it at all to get nicer UX on the Hub that invites the user to create one.
- when uploading a single file (in `push_to_hub`), better use `upload_file` rather than making a local copy to tmp folder  
- make `commit_message` optional
- when creating a repo, do not set `private=False`. This is already the default behavior in `huggingface_hub` (no need to pass it) and we might change it in the future (for example having a setting in your org/user settings on the Hub to decide if new repos must be public/private by default).
- after `create_repo`, use `repo_url.repo_id` as repo_id. Safer this way since `create_repo` handles implicit repo id (e.g. `"my-cool-model"`) while other methods requires an explicit one (e.g. `"Wauplin/my-cool-model"`).

**Disclaimer:** I haven't tested these changes locally :see_no_evil:  

cc @simoninithomas ?

### CODE REVIEW

**Comment by Wauplin** [comment]
I tried to fix the CI tests (pytest was not installed) but I'm still getting a [`ModuleNotFoundError: No module named 'stable_baselines3'`](https://github.com/huggingface/huggingface_sb3/actions/runs/9683292341/job/26718377862?pr=43). Any idea how to fix this?

**Comment by qgallouedec** [comment]
It should be good now (we just need to have a secret token, but I don't have enough rights on this repo for this operation)

**Comment by simoninithomas** [comment]
@qgallouedec I gave you admin privileges if you want to add the secret token for this merge and make some update in the future.

**Comment by Wauplin** [comment]
Yay! :tada: Thanks @qgallouedec for taking care of the CI!

**Pull request merged**
